### ISSUE TITLE
Missing conflicts in tslint-check script result

### ISSUE THREAD

**Issue by tenretC** [alexjoverm/tslint-config-prettier#104]
Hello,

I'm pretty new with Angular and I'm working on a project where I need to use TSLint and Prettier together.
Before I used your project, I looked to every option I use in my tslint config file (tslint.json) to comment them when Prettier handled them.
The thing is I have 3 parameters that I think can conflict after I looked at the tslint-check script result :
- indent
- no-trailing-whitespace
- trailing-comma

For the first two options, I think Prettier handle them automatically and for the last one, you can choose if you want trailing comma or not in the .prettierrc config file.
So is it 3 conflicts between Prettier and TSLint or not ?

**Comment by alexjoverm** [comment]
Hi @tenretC, yes you can remove those rules from your tslint.json and let prettier handle it ;). Those rules are disabled when using this package as well.

**Comment by tenretC** [comment]
thanks for your quick response =)
