### ISSUE TITLE
About testing

### ISSUE THREAD

**Issue by ikatyang** [alexjoverm/tslint-config-prettier#11]
Continue https://github.com/alexjoverm/tslint-config-prettier/issues/8#issuecomment-322700128.

I'd prefer using my structure ([unit tests](https://github.com/ikatyang/tslint-config-prettier-ext/tree/master/rules/tslint) using [some transformer](https://github.com/ikatyang/tslint-config-prettier-ext/blob/master/src/transform/process.ts) to generate tests), what do you think?

**Comment by alexjoverm** [comment]
It looks promising indeed. I've been giving a second peek to the test folders and they look well organized, keeping each test atomic. I have some questions:

 - How easy to maintain is it? Could you describe what steps take to test a new rule? (I suppose copy/paste one of those folders under `rules` and adapt, but want to be sure)
 - What's the generated test thing? What's the `process.ts` file doing and why the code is a string? Could you describe this process in depth?
 - Related with the previous, what's in `src/runtime`?

And a consideration:

 - If possible, I'd like the files we need under your `src` folder to be javascript. But if its really needed or convenient to be ts files, I don't mind. I just wanted to keep it as lean as possible.

**Comment by ikatyang** [comment]
> How easy to maintain is it? Could you describe what steps take to test a new rule? (I suppose copy/paste one of those folders under rules and adapt, but want to be sure)

Yes, as you said, it just needs to copy/paste and modify the rule name and the test case, that's it.

> What's the generated test thing? What's the process.ts file doing and why the code is a string? Could you describe this process in depth? If possible, I'd like to try it myself, some guidance on the steps to do so are appreciated as well.

It's a [jest preprocessor](https://facebook.github.io/jest/docs/en/configuration.html#transform-object-string-string), jest will transform those test case into the real test file so as to test them. (just like [ts-jest](https://github.com/kulshekhar/ts-jest), but I'm transforming test cases to real tests, so that we don't have to write lots of duplicate test code)

> Related with the previous, what's in src/runtime?

They can be also written in the `process.ts`, but it'd be better to write them in another file and import them so that we can get better support by tools, e.g. IDE, typescript's type check, we can't get any hint from the template string in `process.ts`.

> Do you know if the logic of this test could be somehow reused for #3? Don't worry about this very much, just a side question.

I haven't saw it at tslint's docs, but I think something similar can be found in their source code, needs further investigate.

> If possible, I'd like the files we need under your src folder to be javascript. But if its really needed or convenient to be ts files, I don't mind. I just wanted to keep it as lean as possible

I think ts file is more suitable since ts file itself is a good doc and also type-safe, and most of our consumers should be typescript programmer so that I think there won't be problems to write them in typescript.

> Let's make tslint-config-prettier a more robust package with your work :)

:)

**Comment by alexjoverm** [comment]
Thanks for the info.

I'll need more details about the preprocessor thing... How does it work? How can I debug if I need to change something?

**Comment by alexjoverm** [comment]
In the meanwhile you answer, just wanted to say that I'm ok with it, so you can open a PR and we can iterate over it ;).

Some considerations:

 - Let's keep `src` folder for the rulesets, and create a `tools` folder for the runtime and so on
 - Please use camelCase instead of sneak_case (including the preprocess)
 - I'd add a `expect(errorCountAfter).toBe(0)` line at https://github.com/ikatyang/tslint-config-prettier-ext/blob/master/src/transform/process.ts#L46

**Comment by ikatyang** [comment]
> I'll need more details about the preprocessor thing... How can I debug if I need to change something?

It's just a string to string function, you can pass the source text to generate the transformed code and then just debug it as usual. The current test process is simple enough so I didn't write tests for them.

---

 > I'd add a expect(errorCountAfter).toBe(0)

The reason I write `expect(error_count_after).not.toBe(error_count_before)` is that there are some counter-rules, which means their rule is conflict with prettier's behavior, the `errorCountAfter` will never get `0` for those cases, for example:

([`tslint-divid/no-semicolon-interface`](https://github.com/jonaskello/tslint-divid#no-semicolon-interface))

```ts
// rule fail
interface Foo {
  bar: string;
  zoo(): number;
}

// rule pass
interface Foo {
  bar: string, // <---- but prettier prefer `;`, so it'll never get 0 error after formatting
  zoo(): number,
}
```

**Comment by alexjoverm** [comment]
But the point of this package is to disable all rules that conflict with Prettier... Why would be this case different if we set that rule to false?

**Comment by ikatyang** [comment]
Uh, sorry for the confusing, what I mean the `errorCounter` is the counter for the rule (e.g. `tslint-divid/no-semicolon-interface`), to ensure the rule will be affected before/after formatting.

Steps to test:

- lint the source code (**enable the rule**) <---- before
- lint the formatted code (**enable the rule**) <---- after
- their result should be different so as to ensure that rule is exactly affected by prettier.
- the count of errors must be 0 after we **disable the rule**, so we don't need to test it.
