### ISSUE TITLE
Silence tslint-config-prettier-check on success

### ISSUE THREAD

**Issue by astorije** [alexjoverm/tslint-config-prettier#133]
Linting tools (such as TSLint or ESLint) often do not output anything by default when there is nothing to report. I have integrated `tslint-config-prettier-check` in my linting workflow which is really nice to make sure no broken configurations sneak in:

```
$ yarn lint
yarn run v1.5.1
$ run-s lint:* tslint-check
$ tslint --format stylish bin/**/*.ts
$ tslint --format stylish --project .
$ tslint-config-prettier-check ./tslint.yml
No conflict rule detected in ./tslint.yml
✨  Done in 10.76s.
```

It would be nice if the default case would not return anything as well. I don't think it's worth adding a `--verbose` flag (and potential dependency) to get the current way back, but you tell me :)
I'll open a PR in case you find this reasonable, but if you don't like the idea, I'll understand!

**Comment by ikatyang** [comment]
Make sense.
