### ISSUE TITLE
extends expects a string with a relative path

### ISSUE THREAD

**Issue by JeffUberman** [alexjoverm/tslint-config-prettier#143]
I may be misunderstanding something ,but `extends` expects a string with a relative path, not an array:

```
{    
  "extends": [ // Incorrect type: Expected string
    "tslint:latest",
    "tslint-config-prettier"
  ],
  "compilerOptions": { ...
```

**Comment by ikatyang** [comment]
It should [accept both `string` or `string[]`](https://palantir.github.io/tslint/usage/configuration/), I'm not sure how did you get that message.
