### ISSUE TITLE
Support angular-tslint-rules rules

### ISSUE THREAD

**Issue by rafa-as** [alexjoverm/tslint-config-prettier#178]
Add support to use prettier with angular-tslint-rules, a very useful rules to develop Angular +2 projects:

https://github.com/ng-seed/angular-tslint-rules

**Comment by ikatyang** [comment]
Hi, it seems [`angular-tslint-rules`](https://github.com/ng-seed/angular-tslint-rules) is just a sharable config that uses rules from [`tslint`](https://github.com/palantir/tslint) and [`codelyzer`](https://github.com/mgechev/codelyzer), which is [already supported](https://github.com/alexjoverm/tslint-config-prettier#more-configuration).
