### ISSUE TITLE
CLI helper tool

### ISSUE THREAD

**Issue by jaydp17** [alexjoverm/tslint-config-prettier#3]
Provide a CLI helper tool just as [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier#cli-helper-tool) provides.

**Comment by alexjoverm** [comment]
Currently tslint cli doesn't provide a "print config" option. But, we can still do that from our side, just like it is done in this [file from tslint source code](https://github.com/palantir/tslint/blob/master/src/configuration.ts#L202).

PR welcome :)
