### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by alexjoverm** [alexjoverm/tslint-config-prettier#38]
There is a small section [already in this project](https://github.com/alexjoverm/tslint-config-prettier#contributing), but as a good practise a CONTRIBUTING.md file should be added.

You can find info about good practise to write it in [Github open source guide](https://opensource.guide/starting-a-project/#writing-your-contributing-guidelines)

**Comment by drashti4** [comment]
I have added it and linked with readme.md Please review it

**Comment by alexjoverm** [comment]
Closed by #49 and #41
