### ISSUE TITLE
Add examples section to README.md with links

### ISSUE THREAD

**Issue by alexjoverm** [alexjoverm/tslint-config-prettier#39]
I've got a couple of links that can be added:

 - https://alexjoverm.github.io/2017/06/12/Use-Prettier-with-TSLint-and-be-happy/
 - https://egghead.io/lessons/typescript-use-prettier-with-tslint-without-conflicts-c39670eb

But feel free to add any other that you'd like

**Comment by rowhitswami** [comment]
I added example section in README.md, please review @alexjoverm :blush:

**Comment by alexjoverm** [comment]
Closed by #43
