### ISSUE TITLE
support for additional rule sets

### ISSUE THREAD

**Issue by tomdavidson** [alexjoverm/tslint-config-prettier#5]
thank you!

What is involved to support turning off formatting rules from other rule sets such as tslint-microsoft-contrib or tslint-config-airbnb ?

**Comment by alexjoverm** [comment]
Hi @tomdavidson! Thanks and sorry about the late response!

Do they implement any extra rules? If yes, then it would be identifying which ones are formatting rules. Those are the ones that change code appearance, such indent, whitespaces, semicolon, etc.

Once identified, just add them to [index.js](https://github.com/alexjoverm/tslint-config-prettier/blob/master/src/index.js) and make sure test are passing.

**Comment by alexjoverm** [comment]
Thanks to @ikatyang we can close this issue, lot's of rulesets have been added!
