### ISSUE TITLE
Question about scope of tslint-config-prettier...

### ISSUE THREAD

**Issue by maku** [alexjoverm/tslint-config-prettier#7]
This project is not about using rules from tslint.json for prettier formatting, right?

It is only about conflicts? If the answer it yes - is there anything available which uses tslint.json for configuration of prettier?

**Comment by alexjoverm** [comment]
It's for avoiding conflicts, and honestly have no idea if there is something for what you want. It doesn't make much sense, since the idea is to let Prettier handle the formatting.

**Comment by paulrehkugler** [comment]
If you want lint errors if your code doesn't conform to prettier rules, you will want to use the prettier plugin for tslint: https://github.com/ikatyang/tslint-plugin-prettier
