### ISSUE TITLE
Package version?

### ISSUE THREAD

**Issue by KSuttle-cng** [alexjoverm/tslint-config-prettier#73]
Package.json says `0.0.0-development`, but npm says `1.6.0`. I see support for Prettier 1.9 was added, but no version bump happened in this package. Is there a plan to bump or am I missing something fundamental (likely ;) )?

**Comment by ikatyang** [comment]
There's no breaking things introduced in Prettier 1.9, so we don't have to bump version.

For the `0.0.0-development` in `package.json`, that's how [semantic-release](https://github.com/semantic-release/semantic-release) worked, you can see the actual version [here](https://github.com/alexjoverm/tslint-config-prettier/releases).

**Comment by KSuttle-cng** [comment]
Thanks!
