### ISSUE TITLE
Merge repo request

### ISSUE THREAD

**Issue by ikatyang** [alexjoverm/tslint-config-prettier#8]
Hi, I used to think you looks inactive on this repo (#6), so I created another repo [tslint-config-prettier-ext](https://github.com/ikatyang/tslint-config-prettier-ext) (just before the time you respond to my issue 😅) for extending this repo (fully-tested + many rule sets).

But now it seems you're just too busy to maintain this repo frequently, any chance to merge my repo into this one? and I'm willing to help you maintaining this repo. (since the structure is a little different, I'd like to know what do you think about it first)

Additionally, I created a tslint plugin for prettier ([tslint-plugin-prettier](https://github.com/ikatyang/tslint-plugin-prettier)), which is the TSLint version of [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier), you might be interested in it.

**Comment by alexjoverm** [comment]
Hi @ikatyang! Yeah well it's hard sometimes to find time to maintain open source projects, so any help is much appreciated.

Nice work with those packages, they are indeed tested and well documented. 

About integrating the repo, I think we can reuse some stuff. This are my thoughts:

 - Honestly, IMO I see it over-complicated for what it is: to disable some rules I see there are too many files, folders, plus lots of extra code. Not saying this in a negative way. But I'd rather like to keep it simple as it is now, and if at some point is needed to apply more engineering then do it.
 - On the other hand, I've seen you cover more rules with their own tests, that's great! I'm open to integrate them in this repo if you're up to. I planned to do this as requests come and there is already one #5 

And it'd be super awesome if you wanna help maintaining the repo. This is a small one, but any help is always very appreciated :).

So if you'd like, feel free to send any PR to integrate those rulesets/tests. In that case, it'd be keeping the current structure: a file for the rules, and one test file per ruleset.

**Comment by ikatyang** [comment]
> Honestly, IMO I see it over-complicated for what it is: to disable some rules I see there are too many files, folders, plus lots of extra code. Not saying this in a negative way. But I'd rather like to keep it simple as it is now, and if at some point is needed to apply more engineering then do it.

The main issue I want to solve is that some rules will conflict with each other or even conflict with prettier's behavior, so that the only way to test them is to have their own tslint.json and see if the lint meesage changed (become no error or more errors).

And indeed my structure looks a little complicated, but you can see the result in __snapshots__ folder, it's quite easy to understand what does this test doing, and there's no need to modify files from src folder, adding a rule test for a new rule is very easy to do (just have to add a test.ts and a tslint.json).

**Comment by zimme** [comment]
I would love to see this happen, I'm all for projects merging and people helping each other instead if having split packages for pretty much the same thing. =)

**Comment by alexjoverm** [comment]
@ikatyang I've read it, but still my statement remains the same. This repo already tests that most of linting rules don't conflict with TSLint, although more can be added. As well as more rules for other plugins, but still I'd like to keep this simple. Please read carefully my comment above, I say more things aside from that ;)

**Comment by ikatyang** [comment]
Sorry but after the second watch into the tests, I have something not understand:

- How does the current test can really test the rule itself indeed conflict with prettier?
  - I saw two [test case](https://github.com/alexjoverm/tslint-config-prettier/blob/e97be77531d8fe15a1e508098080ab39cc4cdd21/test/index.test.js):
    - All rules equal false - this is fine
    - Throws no linting issues - how can this test validate they're actually conflict?
      - I saw 2 things:
        - test command `"test:lint": "tslint 'test-lint/**'"`
        - tslint.json:  `"extends": ["tslint:latest", "tslint-react", "./src/index.js"]`
      - it looks like you disable all the rules and says "they're now not conflict at all", looks weird to me...
      - how can you confirm it changed before/after (without trying it manually)? I haven't seen it anywhere.
      - and looks at my issue #6's [solution](https://github.com/alexjoverm/tslint-config-prettier/commit/e97be77531d8fe15a1e508098080ab39cc4cdd21), there's even no tests added 😱😱😱
- I mean the anti-rules is something like [this](https://github.com/jonaskello/tslint-divid#no-semicolon-interface), it'll be passed before formatting and failed after formatting, there's no option for this rule in prettier.
- For unit tests, there's always something like A rule conflict with B rule, they can't be tested simultaneously.

I'd like to keep it simple too, but I have no idea how to keep it simple and also fully-tested it without something you feel "over-complicated", is now the time "if at some point is needed to apply more engineering then do it"?

**Comment by alexjoverm** [comment]
The current test suite, which as you said is not 100% covered, tests that a rule is indeed disabled by intentionally writing badly formatted code and check if it throws any linting errors. That's also the way it's done in eslint-config-prettier, and for now it's ok. 

We can improve it by doing what you said, although for me it's more important right now to have more rulesets, such `codelyzer` and so on, and coverage with the current test suite. I see you have implemented more rulesets on your repo.

Additionally, I think is a good point now to create a separate directory for each ruleset, which right now they are all in `index.js`

What do you think about this?

**Comment by ikatyang** [comment]
I don't know how eslint-config-prettier tests, but I think there should have some before/after changes to confirm that the rule is indeed conflict. (how can they confirm it without running prettier?! It looks too magical 😱😱😱, there should be some linting logs for before/after formatting)

About the coverage, my first thought is that I can automatically generate conflict rules by running through those rulesets' test cases, but the truth is some of them are not using official way (TSLint's `*.ts.lint` file) to test rules, so that the only way to get it covers well is to update while some rulesets updated (pin their version and use something like Greenkeeper/Renovate to notice their release, that's what [I did in my repo](https://github.com/ikatyang/tslint-config-prettier-ext/pull/21)).

I think the easiest way is to make a merge repo PR directly, I can do it immediately if you'd like me to. 😅

**Comment by alexjoverm** [comment]
That sounds great! Just to make sure we're on the same page:

 - Let's do one PR for adding the rulesets, splitting them in different folders
 - Then later let's discuss about the test generation and how to go for it, but in another issue/PR to keep the scope clean

Is that ok for you?

**Comment by ikatyang** [comment]
That's OK 👍

**Comment by ikatyang** [comment]
Open #11 for tracking tests.
